# config_meme_template.yaml
kraken:
  api_key: "YOUR_KRAKEN_API_KEY"
  api_secret: "YOUR_KRAKEN_API_SECRET"
assets:
  - SOLUSD
  - DOGEUSD
  - SHIBUSD
capital: 400
trade_frequency: 120
ml:
  lookback: 60
  prediction_horizon: 1
risk:
  max_drawdown: 0.25
  max_position_size: 0.95
  volatility_threshold: 0.15
leverage: 1.0